---
service:

# University

- type: University and college service
  item:
  - entity: Loyola University Chicago
    subitem:
    - subentity: Faculty Appeals Committee
      position:
      - title: member
        dates:
          begin:
            year: 2022
            month: 8
          end:
            year: 2024
            month: 6

  - entity: Faculty Council, Loyola University Chicago
    subitem:
    - subentity: CAS-Humanities Division
      position:
      - title: representative
        dates:
          begin:
            year: 2021
            month: 1
          end:
            year: 2024
            month: 6
    - subentity: "*Ad hoc* Faculty Handbook Committee"
      position:
      - title: member
        dates:
          begin:
            year: 2019
            month: 10
          end:
      - title: co-chair
        dates:
          begin:
            year: 2021
            month: 1
          end:
            year: 2022
            month: 5
      - title: chair
        dates:
          begin:
            year: 2023
            month: 1
          end:
            year: 2024
            month: 6

  - entity: Undergraduate College, Yale University
    subitem:
    - subentity: Committee on Honors and Academic Standing
      position:
      - title: member
        dates:
          begin:
            year: 2012
            month: 8
          end:
            year: 2015
            month: 5

# Department

- type: Departmental and program service
  item:
  - entity: Department of English, Loyola University Chicago
    subitem:
    - subentity: Department Council
      position:
      - title: member
        dates:
          literal: 2018--2020, 2022--2024

    - subentity: Tenure and Promotion Committee
      position:
      - title: member
        dates:
          literal: 2019--2020, 2022--2024

    - subentity: Undergraduate Programs
      position:
      - title: committee member
        dates:
          begin:
            year: 2016
            month: 8
          end:
            year: 2018
            month: 6

    - subentity: Graduate Programs
      position:
      - title: director
        dates:
          begin:
            year: 2024
            month: 7
      - title: committee member
        dates:
          literal: 2021--2022, 2023--2024 # omitting spring 2023
      - title: placement officer
        dates:
          literal: 2018--2020, 2021--2024 # omitting fall 2020
      - title: MA exam committee
        dates:
          literal: 2017--2018, 2022--2023 # chair AY 2023

    - subentity: Edward Surtz, S.J. Memorial Lecture in the Humanities
      position:
      - title: lecture convener
        dates:
          begin:
            year: 2016
            month: 8
          end:
            year: 2022
            month: 5

  - entity: Interdisciplinary Programs, Loyola University Chicago
    subitem:
    - subentity: Medieval Studies Program
      position:
      - title: interim co-director
        dates:
          begin:
            year: 2019
            month: 8
          end:
            year: 2020
            month: 5

    - subentity: Interdisciplinary Working Group for the Study of Premodern Cultures
      position:
      - title: co-convener
        dates:
          begin:
            year: 2021
            month: 8
          end:

  - entity: Center for Textual Studies and Digital Humanities, Loyola University Chicago
    subitem:
    - subentity: Faculty Advisory Committee
      position:
      - title: member
        dates:
          begin:
            year: 2018
            month: 8
          end:

  - entity: Department of English, Yale University
    subitem:
    - subentity: Aims and Procedures Committee
      position:
      - title: member
        dates:
          begin:
            year: 2012
            month: 8
          end:
            year: 2016
            month: 5

    - subentity: Committee on Lectures and Colloquia
      position:
      - title: member
        dates:
          begin:
            year: 2012
            month: 8
          end:
            year: 2016
            month: 5

    - subentity: Medieval Colloquium
      position:
      - title: faculty convener
        dates:
          begin:
            year: 2012
            month: 8
          end:
            year: 2016
            month: 5

    - subentity: Honors and Prizes Committee
      position:
      - title: member
        dates:
          literal: 2009--2010, 2014--2016

    - subentity: Graduate Admissions Committee
      position:
      - title: member
        dates:
          literal: 2009--2010, 2014--2016

    - subentity: Graduate Studies Committee
      position:
      - title: member
        dates:
          literal: 2010--2011, 2012--2014
      - title: diversity recruitment coordinator
        dates:
          begin:
            year: 2012
            month: 12
          end:
            year: 2013
            month: 4

# Other

- type: Professional service
  item:
  - entity: American Association of University Professors
    subitem:
    - subentity: Loyola University Chicago Chapter
      position:
      - title: vice president
        dates:
          begin:
            year: 2020
            month:

  - entity: "*Filologia Germanica -- Germanic Philology*"
    subitem:
    - subentity: Scientific committee for volume 15 (2023)
      position:
      - title: member

  - entity: Illinois Medieval Association
    subitem:
    - subentity: Conference Committee for the 2018 Meeting
      position:
      - title: co-chair

  - entity: "International *Piers Plowman* Society"
    subitem:
    - subentity: Executive Council
      position:
      - title: member
        dates:
          begin:
            year: 2019
            month: 1
          end:
            year: 2022
            month: 12
      - title: treasurer
        dates:
          begin:
            year: 2020
            month: 1
          end:
            year: 2022
            month: 12
    - subentity: Program Committee for the 2019 Congress
      position:
      - title: member

  - entity: Medieval Academy of America
    subitem:
    - subentity: Local Arrangements Committee for the 2010 Meeting
      position:
      - title: co-chair

  - entity: New England Medieval Conference
    subitem:
    - subentity: Steering Committee
      position:
      - title: member
        dates:
          begin:
            year: 2013
            month:
          end:
            year: 2015
            month:

  - entity: Society for Textual Scholarship
    subitem:
    - subentity: Executive Board
      position:
      - title: member
        dates:
          begin:
            year: 2022
            month:
          end:
            year: 2024
            month:
    - subentity: Program Committee for the 2022 Meeting
      position:
      - title: member
---
